apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - producer.yaml
  - consumer.yaml
  - kafka.yaml
  - opa.yaml
  - trino.yaml

configMapGenerator:
  - name: opa-policies
    files:
      - opa/trino_access_control.rego
  - name: opa-data
    files:
      - opa/data.json
