// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/policy.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "policy/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPolicyRepository is a mock of PolicyRepository interface.
type MockPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyRepositoryMockRecorder
}

// MockPolicyRepositoryMockRecorder is the mock recorder for MockPolicyRepository.
type MockPolicyRepositoryMockRecorder struct {
	mock *MockPolicyRepository
}

// NewMockPolicyRepository creates a new mock instance.
func NewMockPolicyRepository(ctrl *gomock.Controller) *MockPolicyRepository {
	mock := &MockPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyRepository) EXPECT() *MockPolicyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicyRepository) Create(policy *domain.Policy) (*domain.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", policy)
	ret0, _ := ret[0].(*domain.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPolicyRepositoryMockRecorder) Create(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicyRepository)(nil).Create), policy)
}

// Delete mocks base method.
func (m *MockPolicyRepository) Delete(id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPolicyRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPolicyRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockPolicyRepository) GetByID(id uint64) (*domain.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPolicyRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPolicyRepository)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockPolicyRepository) List(page, pageSize int) ([]*domain.Policy, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, pageSize)
	ret0, _ := ret[0].([]*domain.Policy)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPolicyRepositoryMockRecorder) List(page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPolicyRepository)(nil).List), page, pageSize)
}

// Update mocks base method.
func (m *MockPolicyRepository) Update(policy *domain.Policy) (*domain.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", policy)
	ret0, _ := ret[0].(*domain.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPolicyRepositoryMockRecorder) Update(policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicyRepository)(nil).Update), policy)
}
