apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: demo
spec:
  containers:
    - name: producer
      image: public.ecr.aws/h7f0r1p2/demo-kube:producer
      imagePullPolicy: Always
      env:
        - name: KAFKA_BROKER
          value: "kafka-service.demo.svc.cluster.local:9092"
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
